[mgr]
show_hidden = true
ratio = [1, 4, 0]
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
linemode = "size"

[opener]
edit = [
    { run = 'bash ~/.config/scripts/yazi-opener.sh "$@"', block = true, desc = "Edit", for = "unix" }
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },
	{ mime = "text/*", use = [ "edit", "open", "reveal" ] },
	{ mime = "application/json", use = [ "edit", "open", "reveal" ] },
	{ mime = "application/x-sh", use = [ "edit", "open", "reveal" ] },
	{ name = "*", use = [ "edit", "open", "reveal" ] },
]
